# Generated by Django 6.0.5 on 2026-05-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='react_type',
            field=models.CharField(choices=[('Like', 'Like 👍'), ('Love', 'Love ❤️'), ('Haha', 'Haha 😂'), ('Sad', 'Sad 😢'), ('Angry', 'Angry 😡')], default='Like', max_length=50),
        ),
    ]
